### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by Yajo** [DaveJarvis/kmcaster#1]
Hi there!

I've been looking for an alternative to key-mon, which is unmaintained AFAIK and quite buggy these days.

I love kmcaster. Would you find it interesting to package it for https://flathub.org, so it's available for a wider audience at the length of a click?

**Comment by DaveJarvis** [comment]
@Yajo, thank you for the encouragement.

I've written a cross-compiling [script](https://github.com/DaveJarvis/scrivenvar/blob/master/installer) to build self-contained, standalone binaries for another project. The script uses [warp-packer](https://github.com/dgiagio/warp); the project's README references the [latest release](https://github.com/DaveJarvis/scrivenvar/blob/master/README.md#download) for all supported platforms.

Flatpak may support OpenJDK 14 through requirements dependencies. It's a good idea and getting a wider audience has obvious benefits. KmCaster was a [yak shaving](https://en.wiktionary.org/wiki/yak_shaving) project. I may port the installer script to create standalone binaries. Until then, if you'd like to pursue the Flatpak idea, I encourage you to [submit a request](https://discourse.flathub.org/c/requests/5) for adding it.

Although it is a _superb_ idea and great request, I'm going to close this for now; if anyone wants to take action on adding KmCaster to Flathub, I will answer related questions.
