### ISSUE TITLE
Flathub integration is done, what to upstream?

### ISSUE THREAD

**Issue by Yajo** [DaveJarvis/kmcaster#10]
Hi @DaveJarvis. I fixed #1 and now kmcaster can be installed with 1 click on all Linux distros!

- Package: https://www.flathub.org/apps/details/io.github.davejarvis.kmcaster
- Source code: https://github.com/flathub/io.github.davejarvis.kmcaster

There's a few pending points where I'd like to know your opinion.

Now that that job is done, I think it would be cool to [include a badge](https://flathub.org/badges) here upstream, so Linux users can get to the package easily.

According to [app submission docs](https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do):

> We would prefer that these applications are controlled by their authors.

So if you want, I'd be glad to ask Flathub maintainers to donate the package repo to you, or to make you co-maintainer. If you don't, things can stay as they are.

Finally, I had to create some metadata to package your app for Linux desktops. Mainly:

1. [io.github.davejarvis.kmcaster.desktop](https://github.com/flathub/io.github.davejarvis.kmcaster/blob/7addd5ac7faa89a392fafa8e621bf8557487d7ae/io.github.davejarvis.kmcaster.desktop), for the app to appear as a launcher. Pro feature: right-click to start small.
2. [io.github.davejarvis.kmcaster.metainfo.xml](https://github.com/flathub/io.github.davejarvis.kmcaster/blob/7addd5ac7faa89a392fafa8e621bf8557487d7ae/io.github.davejarvis.kmcaster.metainfo.xml), metadata for app stores.
3. [io.github.davejarvis.kmcaster.svg](https://github.com/flathub/io.github.davejarvis.kmcaster/blob/7addd5ac7faa89a392fafa8e621bf8557487d7ae/io.github.davejarvis.kmcaster.svg), the icon, which is itself based on [0.svg](https://github.com/DaveJarvis/kmcaster/blob/1.0.3/src/main/resources/images/mouse/0.svg), but with a square canvas, to avoid desktops displaying it stretched.

The [maintenance guide](https://github.com/flathub/flathub/wiki/App-Maintenance#acceptable-but-should-be-submitted-upstream) says:

> should be submitted upstream

So, if you agree, I can open a PR to move those files here. I'd ask you in which folder do you prefer them.

**Comment by DaveJarvis** [comment]
Thanks for the efforts, @Yajo.

* Is it possible to rename `io.github.davejarvis.kmcaster` to `com.whitemagicsoftware.kmcaster`, so that the references align with the Java package?
* Instead of "Launch small" what do you think of "Launch 50px"?
* That icon is fine (note that there's a PR for a much better looking UI)

Having a "flatpak" directory off the root directory works.

**Comment by Yajo** [comment]
> Is it possible to rename `io.github.davejarvis.kmcaster` to `com.whitemagicsoftware.kmcaster`, so that the references align with the Java package?

AFAIK that would mean marking the old ID as deprecated and migrated to a new one, and having to go again through the app submission process. @nedrichards can tell better.

If that's the case, IMHO the effort is not worth it.

> Instead of "Launch small" what do you think of "Launch 50px"?

I think "small" is more user friendly. If somebody really cares about the exact size, they can use the CLI directly: `flatpak run io.github.davejarvis.kmcaster --dimension=40`.

After all, the normal launch also doesn't specify it's 100px, and it doesn't seem to be a problem... 🤷🏼‍♂️ 



> That icon is fine (note that there's a PR for a much better looking UI)

Where's the PR? I don't find it 🤔 



> Having a "flatpak" directory off the root directory works.

Nice, thanks! I'll submit a PR with these changes then when I have some time.

**Comment by DaveJarvis** [comment]
> Nice, thanks! I'll submit a PR with these changes then when I have some time.

Sorry, I meant there's a ticket with better looking icons. They are tucked away in the attached file.

[kmcaster.zip](https://github.com/DaveJarvis/kmcaster/files/6190850/kmcaster.zip)

unzip -v kmcaster.zip | grep svg$

"Launch small" is fine.

Please see if the name change isn't very arduous, I'd _strongly_ prefer for it not to be GitHub-specific and not include my name.

**Comment by Yajo** [comment]
Track the rename progress in https://github.com/flathub/flathub/pull/2182.
