### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by Falcon2840** [DaveJarvis/kmcaster#12]
Ubuntu 21.04 (hirsute) will soon be available with Wayland as the default graphics manager. I noticed that the program (WHICH IS SIMPLE AMAZING) only displays data when its own "window" is active. Nothing is displayed when using any other program (such as GEdit). Did I do something wrong, or is there really a problem with Wayland graphics support?

Thank you in advance for your help...

**Comment by DaveJarvis** [comment]
KmCaster uses the JNativeKeyHook library for intercepting mouse/keyboard events. There's a ticket opened for supporting Wayland:

https://github.com/kwhat/jnativehook/issues/211

Until that library fully supports Wayland, there's not much KmCaster can do. If you know of any keyboard/mouse event libraries for Java that support X11, Windows, Wayland, and MacOS flavours, please let us know.

**Comment by Falcon2840** [comment]
Thanks for the quick response!

Then I'll move on to solving the problem ... (I first selected Ubuntu Xorg mode on the Ubuntu 21.04 Login screen, which solved the problem.)
However, since Canonical I feel is "forcing" the Wayland basics again, others will be sure to take care of it. (See VokoScreen program!) :(

**Comment by DaveJarvis** [comment]
Glad you found a workaround! Closing this ticket. When JNativeKeyHook is updated to support Wayland, we should get a notification that its ticket 211 has been closed. At that point, it should be a matter of updating the `build.gradle` file to use the new version and then rebuilding KmCaster.
