### ISSUE TITLE
Can not get out of Kmcaster. 

### ISSUE THREAD

**Issue by ChiefHart** [DaveJarvis/kmcaster#16]
The recomended [Alt]+[F4] does notwork.  I can not find any way to get the dang thing off my screen, and I have two of them on the screen.  This is a stupid program as there is no way out.

**Comment by DaveJarvis** [comment]
Sorry to read you're having issues with the program. On Linux or Windows try:

1. Click the window to give it focus.
1. Press <kbd>Alt+F4</kbd> to quit.

If that still doesn't work for you, feel free to re-open the ticket with additional information, such as: operating system version and any error messages.
