### ISSUE TITLE
Still can not close the application (Alt+F4 does not work)

### ISSUE THREAD

**Issue by ChiefHart** [DaveJarvis/kmcaster#17]
Ok, I tried again and alt + F4 does nothing.
I am using a distro of Linux:  POP!_OS 20.04LTS and it is based on Ubuntu and is authored by System76.
I am using a System76 Darter Pro 7 laptop.  CPU is 11th Gen Intel® Core i7-1165G7, 500 GB NVMe, 32-GB RAM.
Except for not being able to close the application it really is neat and displays every button push and keystroke.
I hope the additional info helps.

**Comment by DaveJarvis** [comment]
I don't know why it won't close for you. If `pgrep` is installed, you can use a shorter version:

``` bash
kill -9 $(pgrep -f kmcaster)
```

Alternatively, run the following command from a terminal, twice (once for each running instance):

``` bash
 kill -9 $(ps auxw | grep -i [k]mcaster | head -1 | awk '{print $2}')
```

* The `kill` command will force an application to quit.
* The `ps` command lists all actively running processes.
* The `grep` command filters the list for any processes matching KmCaster; using `[k]` prevents the `grep` command from matching itself.
* The `head` command limits the results to a single instance of KmCaster.
* The `awk` command extracts just the process ID.

Feel free to re-open if the application cannot be killed.
