### ISSUE TITLE
windows version : wrong behaviour

### ISSUE THREAD

**Issue by alezzacreative** [DaveJarvis/kmcaster#20]
this is how the jar file behaves in windows
[](URL)

https://user-images.githubusercontent.com/63913433/194773588-5660648a-5aa8-49ef-ad54-c5213585020e.mp4

the ctrl shift alt keys don't work he only displays them in the last key
the letters are sometimes displayed sometimes just ... dotes
the used font is huge (bold and big} )compared to the graphics 

for the mouse, I fixed that by modifying the SVG files inside the jar file

**Comment by DaveJarvis** [comment]
What version of Java? What version of Windows? What version of KmCaster?

**Comment by alezzacreative** [comment]
hello
its the latest version kmcaster 1.1.0 ,windows 10, java jdk-17.0.4.101
thank you

**Comment by DaveJarvis** [comment]
Please try again using KmCaster version 1.1.1.

**Comment by alezzacreative** [comment]
yes i tried it an hour ago and the problems remains

**Comment by DaveJarvis** [comment]
Closing as resolved.

If the problem persists, please re-open.
