### ISSUE TITLE
a skin proposal and some feature requests

### ISSUE THREAD

**Issue by alezzacreative** [DaveJarvis/kmcaster#3]
hi am alezzacreative am a graphic designer i work with open source software
i changed the the graphics in the app by just replacing the svg files inside the jar and to my surprise it worked
and i have some requests
1 - i dont know but the antialiasing in the borders of the graphics is terrible especially when the background is in lighter colours.
2 - if you can ad an option in the command line to disable the semi transparent background or even better to have also an svg graphic that can be customized as i did with the others.
3 - i tried to replace the font but with no success i was hoping to use a more moden looking font like "inter" https://fonts.google.com/specimen/Inter   even better if we can have fonts folders inside the "fonts" directory so we can choose the font from the command line.
4 - if the spacing between the keys can be adjusted
5 - if we can have a mode where not all "shift ctrl alt" key are always displayed but only shown when pressed like the last how key works.
screenshot
![Screenshot kmcaster](https://user-images.githubusercontent.com/63913433/94828199-23617500-0401-11eb-91f0-0db640091fbe.png)
a video
http://www.mediafire.com/file/pgcot5ycpux7esz/Screencast_kmcaster.mp4/file
my modified version of the app
http://www.mediafire.com/file/nol90ipz9lxr7rq/kmcaster.jar/file
i have other ideas for other skins if you want just ask me
thank you for this handy app

**Comment by DaveJarvis** [comment]
In `Constants.java`, you'll see:

``` java
public static final Font LABEL_FONT = new Font( "DejaVu Sans", BOLD, 100 );
```

You'll have to edit that line to change the font from _DejaVu Sans_ to _Inter_. Once the new fonts are copied into the fonts folder, you should be able to rebuild and see the font appear.

**Comment by DaveJarvis** [comment]
Thank you for the feedback. The issues are separated into the following tickets:

- #4 
- #5 
- #6 

@alezzacreative, please review the new tickets to confirm that all your issues would be addressed.

**Comment by alezzacreative** [comment]
thank you for the reply and indeed all the issues are well explained in the tickets
