### ISSUE TITLE
Can't access settings

### ISSUE THREAD

**Issue by bumbalu** [DaveJarvis/KmCaster#31]
Hi!
I am trying to change preferences (I only need to show mouse buttons clicks) but cannot access settings. 
My system is Linux Mint 21.1 Cinnamon. This is a Flatpack installation from official repo. 
after:
~$ java -jar kmcaster.jar -h
I get: 
Error: Unable to access jarfile kmcaster.jar

Any advice what I can do to change settings?
Thank you!

**Comment by DaveJarvis** [comment]
>  I am trying to change preferences (I only need to show mouse buttons clicks) but cannot access settings.

I don't believe there's a feature to show only mouse clicks.

> This is a Flatpack installation from official repo.

Don't use Flatpack, it doesn't buy you anything.

Download https://github.com/DaveJarvis/KmCaster/releases/download/2.0.0/kmcaster.jar directly from this repo.
