### ISSUE TITLE
Create a configuration file

### ISSUE THREAD

**Issue by DaveJarvis** [DaveJarvis/kmcaster#6]
# Overview

Users want more control over fonts and graphics, which entails adding a configuration file. A simple properties file can contain:

* Font name
* Font colour (key down), including alpha component (i.e., RGBA)
* Font colour (key up), including alpha (i.e., RGBA)
* Path to resources (fonts, images, and background directory)
* Key codes (?)
* On-screen location (x, y)
* Application size (in pixels)
* Spacing (margin) between buttons
* Button insets
* Enable click tracker

Note: Setting the key up/key down colours with alpha allows the key labels to be hidden.

# Technical

Add a command-line option to load a specific configuration file. This will entail changes to the following classes:

* `Constants.java`,
    * `LABEL_FONT` gets settings item
    * `COLOUR_KEY_DN`  gets settings item
    * `COLOUR_KEY_UP`  gets settings item
* `SvgRasterizer` -- use `getResource` by default, but with an option to use external source, which should not require some minor changes to `HardwareImages`; if changes to `HardwareImages` are required, some refactoring may be necessary
* `HardwareImages` -- `SWITCH_INSETS` gets settings items
* `PaddedInsets` -- `INSET_PADDING` gets settings items
* `KmCaster` -- the `init()` method must use settings for on-screen location
* `Settings` -- modify to include aforementioned settings items as well as a new configuration item to point to a properties file --- that properties file has additional settings, which are loaded before the settings are applied (i.e., command-line options always override property file settings)
* `TranslucentPanel` -- update constructor to call `setBorder(javax.swing.border.Border)` (`MarginBorder`?) using settings that define margin between components (hardware images)

**Comment by ifohancroft** [comment]
Any update on this?

**Comment by DaveJarvis** [comment]
> Any update on this?

No. PR welcome.

**Comment by DaveJarvis** [comment]
Closing as this behaviour is provided by Picocli. Re-open if the configuration file is insufficient.
