### ISSUE TITLE
How to change size?

### ISSUE THREAD

**Issue by tylerecouture** [DaveJarvis/kmcaster#7]
I may be blind but I couldnt see how to reduce the overall size of the widget.

Thanks!

**Comment by DaveJarvis** [comment]
Try running using `-h` from the command-line:

``` bash
java -jar kmcaster.jar -h
```

Will show all the available options, including how to change the size.

**Comment by laguill** [comment]
I just installed the flatpack version on ubuntu.
The command to resize the window is not working.

I get this error `Error: Unable to access jarfile kmcaster.jar
`
