### ISSUE TITLE
Please consider adding a feature to add a halo around the mouse pointer

### ISSUE THREAD

**Issue by ShabbyX** [DaveJarvis/kmcaster#9]
Awesome piece of software! One missing feature is accenting the mouse pointer (always, or on events, like click). That helps tremendously to bring to attention of the viewer where the mouse actually is when the click happens.

**Comment by DaveJarvis** [comment]
In `EventHandler.java`, the method `updateMouseStatus` is the entry point for handling on-screen updates whenever a mouse button changes state. In addition to updating the buttons, it is possible to update the screen to visually indicate a click at the mouse's location. A solution would entail:

* Add `isClick` to `HardwareSwitch` that returns `true` if the instance is one of the `MOUSE_` enumerated values.
* Add mouse X & Y positions to `HardwareSwitchState`, ensure they are updated.
* Change `updateMouseStatus` to check if the `hwSwitch` is a mouse click (i.e., `isClick`).

If the `hwSwitch` represents a mouse click in the _pressed_ state, then animate an indicator for the mouse click. Perhaps a [ripple effect](https://github.com/NanBox/RippleLayout/blob/master/ripplelayout/src/main/java/com/nanbox/ripplelayout/RippleLayout.java) or concentric circles.

Note that most operating systems already have accessibility options to emphasize the mouse cursor location. There are third-party tools, as well, that can provide click effects. Having an integrated, cross-platform solution would be handy, though.

**Comment by DaveJarvis** [comment]
Marking as won't fix. There appear to be numerous ways to accomplish this, both with third-party tools and natively.

https://www.youtube.com/watch?v=kwSqtNvT7to

If you really, really, really need it, please re-open with a reason why other software is inadequate.
